site_name: USTC Mirror Help
site_description: USTC Mirror Help
site_author: LUG @ USTC
site_url: https://mirrors.ustc.edu.cn/help/
use_directory_urls: false
repo_name: ustclug/mirrorhelp
repo_url: https://github.com/ustclug/mirrorhelp
copyright: |
  © 版权所有 2017 - 2024, LUG@USTC.
  <br>
  除额外注明的地方外，本文档按 CC BY-NC-SA 4.0 许可协议发布。

theme:
  name: material
  language: zh
  font: false
  favicon: /static/img/favicon.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    logo: material/mirror-rectangle
    repo: octicons/mark-github-16
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.top

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - markdown.extensions.def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path:
        - includes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search:
      lang: zh
  - macros:
      include_dir: includes
      j2_comment_start_string: "{%#"
      j2_comment_end_string: "%}"

extra:
  social:
    - icon: fontawesome/brands/linux
      link: https://lug.ustc.edu.cn/
    - icon: octicons/mark-github-16
      link: https://github.com/ustclug
  analytics:
    provider: google
    property: UA-160637954-1

  # data for use in templates
  debian_releases:
    - version: 12
      codename: bookworm
      proxmox_version: 8
    - version: 11
      codename: bullseye
      proxmox_version: 7
  ubuntu_releases:
    - version: 24.04
      codename: noble
    - version: 22.04
      codename: jammy
    - version: 20.04
      codename: focal
    - version: 18.04
      codename: bionic
    - version: 16.04
      codename: xenial

extra_css:
  - css/extra.css
  - https://mirrors.ustc.edu.cn/static/help/roboto.css
  - https://mirrors.ustc.edu.cn/static/help/roboto-mono/stylesheet.css

nav:
  - 首页: index.md
  - rsync-guide.md
  - quickstart.md
  - contributor.md

  - 发行版镜像:
    - alpine.md
    - anthon.md
    - aosp.md
    - archlinux.md
    - archlinuxarm.md
    - archlinuxcn.md
    - blackarch.md
    - cachyos.md
    - centos.md
    - centos-stream.md
    - centos-vault.md
    - debian.md
    - debian-security.md
    - debian-cd.md
    - debian-cdimage.md
    - debiancn.md
    - deb-multimedia.md
    - epel.md
    - fedora.md
    - freebsd.md
    - freebsd-pkg.md
    - freebsd-ports.md
    - gentoo.md
    - gentoo-portage.md
    - gentoo.git.md
    - immortalwrt.md
    - kali.md
    - linuxmint.md
    - mageia.md
    - manjaro.md
    - msys2.md
    - openeuler.md
    - opensuse.md
    - openwrt.md
    - packman.md
    - proxmox.md
    - raspberry-pi-os-images.md
    - raspbian.md
    - raspbian-addons.md
    - rocky.md
    - rpmfusion.md
    - termux.md
    - termux-its-pointless.md
    - trisquel.md
    - turnkeylinux.md
    - ubuntu.md
    - ubuntu-ports.md
    - ubuntu-old-releases.md
    - ubuntu-releases.md
    - ubuntu-cdimage.md
    - ubuntu-cloud-images.md
  - 语言镜像:
    - clojars.md
    - ghcup.md
    - hackage.md
    - julia.md
    - node.md
    - nodesource.md
    - npm.md
    - pypi.md
    - rubygems.md
    - crates.io-index.md
    - rust-static.md
    - stackage.md
  - 软件镜像:
    - anaconda.md
    - ceph.md
    - CPAN.md
    - CRAN.md
    - docker-ce.md
    - dockerhub.md
    - eclipse.md
    - elpa.md
    - flathub.md
    - github-release.md
    - brew.git.md
    - homebrew-bottles.md
    - homebrew-core.git.md
    - homebrew-cask.git.md
    - homebrew-services.git.md
    - influxdata.md
    - kubernetes.md
    - linux.git.md
    - mariadb.md
    - mozilla.md
    - mysql-repo.md
    - nix-channels.md
    - libnvidia-container.md
    - packaging-gitea.md
    - qtproject.md
    - raspberrypi.md
    - ros.md
    - ros2.md
    - rosdistro.md
    - sagemath.md
    - tailscale.md
    - winget-source.md
    - xbmc.md
